local lib_sources = {'base64.c', 'core.c', 'coretests.c', 'blake2s.c', 'entropy.c',
    'extratests.c', 'fileio.c', 'lineardep.c', 'hwtests.c', 'specfuncs.c',
    'threads_intf.c'}

local bat_sources = {'bat_express.c', 'bat_brief.c', 'bat_default.c',
    'bat_file.c', 'bat_full.c', 'bat_special.c'}

local lib_headers = {'apidefs.h', 'cinterface.h', 'base64.h', 'blake2s.h', 'core.h',
    'coredefs.h', 'coretests.h', 'entropy.h', 'extratests.h', 'fileio.h',
    'hwtests.h', 'int128defs.h', 'lineardep.h', 'specfuncs.h',
    'threads_intf.h', 'x86exts.h'}


-- List of all generators; all of them are portable and have at least some
-- cross-platform variants.
local gen_sources = {
    'a5rand',             'a5rand32',           'a5rand32w',          'a5randw', 
    'aes128',             'alfib',              'alfib64x5',          'alfib8x5', 
    'alfib_lux',          'alfib_mod',          'ara32',              'arxfw16', 
    'arxfw16ex2',         'arxfw32',            'arxfw64',            'arxfw8', 
    'arxfw8ex',           'arxfw8ex2',          'arxfw8ex3',          'biski16', 
    'biski16_alt',        'biski16_mul',        'biski32',            'biski32_alt', 
    'biski64',            'biski64sh',          'biski64_alt',        'biski64_mul', 
    'biski8',             'biski8_alt',         'biski8_mul',         'blabla', 
    'chacha',             'cmwc4096',           'cmwc4827',           'combo', 
    'coveyou64',          'cswb4288',           'cswb4288_64',        'cwg64', 
    'des',                'drand48',            'efiix64x48',         'flea32x1', 
    'gjrand16',           'gjrand32',           'gjrand64',           'gjrand8', 
    'gmwc128',            'hc256',              'hicg64',             'ia', 
    'ia64',               'ibaa',               'icg31x2',            'icg64', 
    'icg64_p2',           'isaac',              'isaac64',            'jctr32', 
    'jctr64',             'jkiss',              'jkiss32',            'jlkiss64', 
    'kiss11_32',          'kiss11_64',          'kiss4691',           'kiss64', 
    'kiss93',             'kiss96',             'kiss99',             'komirand', 
    'komirand16',         'komirand16w',        'komirand32',         'komirand32w', 
    'komirandw',          'kuzn',               'lcg128',             'lcg32prime', 
    'lcg42',              'lcg64',              'lcg64prime',         'lcg64sc', 
    'lcg64sc2',           'lcg69069',           'lcg96',              'lea', 
    'lfib4',              'lfib4_u64',          'lfib_par',           'lfib_ranmar', 
    'lfsr113',            'lfsr258',            'loop_7fff_w64',      'lrnd64_1023', 
    'lrnd64_255',         'lxm_64x128',         'macmarsa',           'magma', 
    'melg19937',          'melg44497',          'melg607',            'minstd', 
    'mixmax',             'mlfib17_5',          'mrg32k3a',           'msws', 
    'msws64',             'msws64x',            'msws_ctr',           'mt19937', 
    'mt19937_64',         'mtc16',              'mtc32',              'mtc64', 
    'mtc64hi',            'mtc8',               'mularx128',          'mularx128_str', 
    'mularx128_u32',      'mularx256',          'mularx64_r2',        'mularx64_u32', 
    'mulberry32',         'mwc128',             'mwc128x',            'mwc128xxa32', 
    'mwc1616',            'mwc1616p',           'mwc1616x',           'mwc16_32', 
    'mwc256xxa64',        'mwc3232x',           'mwc32x',             'mwc32xxa8', 
    'mwc40xxa8',          'mwc4691',            'mwc48xxa16',         'mwc63x2', 
    'mwc64',              'mwc64x',             'mwc64_2p58',         'mwc8222', 
    'mzran13',            'ncombo',             'pcg32',              'pcg32_dxsm', 
    'pcg32_xsl_rr',       'pcg64_64',           'pcg64_dxsm',         'pcg64_xsl_rr', 
    'philox',             'philox2x32',         'philox32',           'prvhash12c', 
    'prvhash12cw',        'prvhash16c',         'prvhash16cw',        'prvhash64c', 
    'prvhash64cw',        'r1279',              'r250',               'ran', 
    'randu',              'ranlux48',           'ranluxpp',           'ranq1', 
    'ranq2',              'ranrot16tiny',       'ranrot32',           'ranrot32tiny', 
    'ranrot64tiny',       'ranrot8tiny',        'ranrot_bi',          'ranshi', 
    'ranval',             'ranval64',           'rc4',                'rc4ok', 
    'rdrand',             'rge256ex',           'rge256exctr',        'rge256lite', 
    'rge512ex',           'rge512exctr',        'romutrio',           'rrmxmx', 
    'sapparot',           'sapparot2',          'sapparot2_64',       'seed', 
    'seiran128',          'sezgin63',           'sfc16',              'sfc32', 
    'sfc64',              'shioi128',           'sfc8',               'shr3', 
    'skiss32',            'skiss64',            'smwc16x8',           'smwc192', 
    'smwc192lux',         'smwc24',             'smwc48',             'smwc48lux', 
    'smwc8x16',           'smwc96',             'speck128',           'speck128sc', 
    'speck64_128',        'splitmix',           'splitmix32',         'splitmix32cbc', 
    'splitmix_g1',        'sqxor',              'sqxor32',            'stormdrop', 
    'superduper64',       'superduper73',       'superduper96',       'swb', 
    'swblarge',           'swblux',             'swbmwc32',           'swbmwc64', 
    'swbw',               'taus88',             'threefish1024',      'threefry', 
    'threefry2x64',       'tinymt32',           'tinymt64',           'tylo64', 
    'ultra',              'ultra64',            'v3b',                'well1024a', 
    'weyl',               'wich1982',           'wich2006',           'wob2m', 
    'wyrand',             'xabc16',             'xabc32',             'xabc64', 
    'xabc8',              'xkiss16sh_awc',      'xkiss16_awc',        'xkiss32sh_awc', 
    'xkiss32_awc',        'xkiss64_awc',        'xkiss8_awc',         'xorgens', 
    'xoroshiro1024st',    'xoroshiro1024stst',  'xoroshiro128',       'xoroshiro128aox', 
    'xoroshiro128p',      'xoroshiro128pp',     'xoroshiro128pp_vec', 'xoroshiro32', 
    'xoroshiro32pp',      'xoroshiro64pp',      'xoroshiro64st',      'xoroshiro64stst', 
    'xorshift128',        'xorshift128p',       'xorshift128pp',      'xorshift128rp', 
    'xorshift64',         'xorshift64st',       'xorwow',             'xoshiro128p', 
    'xoshiro128pp',       'xoshiro256p',        'xoshiro256pp',       'xoshiro256stst', 
    'xsh',                'xtea',               'xtea2',              'xtea2_64', 
    'xxtea',              'ziff98'
}

return {
    get_lib_headers = function() return lib_headers end,
    get_lib_sources = function() return lib_sources end,
    get_bat_sources = function() return bat_sources end,
    get_gen_sources = function() return gen_sources end
}
