local lib_sources = {'base64.c', 'core.c', 'coretests.c', 'blake2s.c', 'entropy.c',
    'extratests.c', 'fileio.c', 'lineardep.c', 'hwtests.c', 'specfuncs.c',
    'threads_intf.c'}

local bat_sources = {'bat_express.c', 'bat_brief.c', 'bat_default.c',
    'bat_file.c', 'bat_full.c', 'bat_special.c'}

local lib_headers = {'apidefs.h', 'cinterface.h', 'base64.h', 'blake2s.h', 'core.h',
    'coredefs.h', 'coretests.h', 'entropy.h', 'extratests.h', 'fileio.h',
    'hwtests.h', 'int128defs.h', 'lineardep.h', 'specfuncs.h',
    'threads_intf.h', 'x86exts.h'}


-- List of all generators; all of them are portable and have at least some
-- cross-platform variants.
local gen_sources = {
    'a5rand',             'a5rand32',           'a5rand32w',          'a5randw', 
    'aes128',             'alfib',              'alfib64x5',          'alfib8x5', 
    'alfib',              'alfib',              'ara32',              'arxfw16', 
    'arxfw64',            'arxfw8',             'arxfw8ex',           'biski16', 
    'biski16',            'biski16',            'biski32',            'biski32', 
    'biski64',            'biski64sh',          'biski64',            'biski64', 
    'biski8',             'biski8',             'biski8',             'blabla', 
    'chacha',             'cmwc4096',           'cmwc4827',           'combo', 
    'coveyou64',          'cswb4288',           'cswb4288',           'cwg64', 
    'des',                'drand48',            'efiix64x48',         'flea32x1', 
    'gjrand16',           'gjrand32',           'gjrand64',           'gjrand8', 
    'gmwc128',            'hc256',              'hicg64',             'ia', 
    'ia64',               'ibaa',               'icg31x2',            'icg64', 
    'icg64',              'isaac',              'isaac64',            'jctr32', 
    'jctr64',             'jkiss',              'jkiss32',            'jlkiss64', 
    'kiss11',             'kiss11',             'kiss4691',           'kiss64', 
    'kiss93',             'kiss96',             'kiss99',             'komirand', 
    'komirand16',         'komirand16w',        'komirand32',         'komirand32w', 
    'komirandw',          'kuzn',               'lcg128',             'lcg32prime', 
    'lcg42',              'lcg64',              'lcg64prime',         'lcg64sc', 
    'lcg64sc2',           'lcg69069',           'lcg96',              'lea', 
    'lfib4',              'lfib4',              'lfib',               'lfib', 
    'lfsr113',            'lfsr258',            'loop',               'lrnd64', 
    'lrnd64',             'lxm',                'macmarsa',           'magma', 
    'melg19937',          'melg44497',          'melg607',            'minstd', 
    'mixmax',             'mlfib17',            'mrg32k3a',           'msws', 
    'msws64',             'msws64x',            'msws',               'mt19937', 
    'mt19937',            'mtc16',              'mtc32',              'mtc64', 
    'mtc64hi',            'mtc8',               'mularx128',          'mularx128', 
    'mularx128',          'mularx256',          'mularx64',           'mularx64', 
    'mulberry32',         'mwc128',             'mwc128x',            'mwc128xxa32', 
    'mwc1616',            'mwc1616p',           'mwc1616x',           'mwc16', 
    'mwc256xxa64',        'mwc3232x',           'mwc32x',             'mwc32xxa8', 
    'mwc40xxa8',          'mwc4691',            'mwc48xxa16',         'mwc63x2', 
    'mwc64',              'mwc64x',             'mwc64',              'mwc8222', 
    'mzran13',            'ncombo',             'pcg32',              'pcg32', 
    'pcg32',              'pcg64',              'pcg64',              'pcg64', 
    'philox',             'philox2x32',         'philox32',           'prvhash12c', 
    'prvhash12cw',        'prvhash16c',         'prvhash16cw',        'prvhash64c', 
    'prvhash64cw',        'r1279',              'r250',               'ran', 
    'randu',              'ranlux48',           'ranluxpp',           'ranq1', 
    'ranq2',              'ranrot16tiny',       'ranrot32',           'ranrot32tiny', 
    'ranrot64tiny',       'ranrot8tiny',        'ranrot',             'ranshi', 
    'ranval',             'ranval64',           'rc4',                'rc4ok', 
    'rge256ex',           'rge256exctr',        'rge256lite',         'rge512ex', 
    'rge512exctr',        'romutrio',           'rrmxmx',             'sapparot', 
    'sapparot2',          'sapparot2',          'seed',               'sezgin63', 
    'sfc16',              'sfc32',              'sfc64',              'sfc8', 
    'shr3',               'skiss32',            'skiss64',            'smwc16x8', 
    'smwc192',            'smwc192lux',         'smwc24',             'smwc48', 
    'smwc48lux',          'smwc8x16',           'smwc96',             'speck128', 
    'speck128sc',         'speck64',            'splitmix',           'splitmix32', 
    'splitmix32cbc',      'splitmix',           'sqxor',              'sqxor32', 
    'stormdrop',          'superduper64',       'superduper73',       'superduper96', 
    'swb',                'swblarge',           'swblux',             'swbmwc32', 
    'swbmwc64',           'swbw',               'taus88',             'threefish1024', 
    'threefry',           'threefry2x64',       'tinymt32',           'tinymt64', 
    'tylo64',             'ultra',              'ultra64',            'v3b', 
    'well1024a',          'weyl',               'wich1982',           'wich2006', 
    'wob2m',              'wyrand',             'xabc16',             'xabc32', 
    'xabc64',             'xabc8',              'xkiss16sh',          'xkiss16', 
    'xkiss32sh',          'xkiss32',            'xkiss64',            'xkiss8', 
    'xorgens',            'xoroshiro1024st',    'xoroshiro1024stst',  'xoroshiro128', 
    'xoroshiro128aox',    'xoroshiro128p',      'xoroshiro128pp',     'xoroshiro128pp', 
    'xoroshiro32',        'xoroshiro32pp',      'xoroshiro64pp',      'xoroshiro64st', 
    'xoroshiro64stst',    'xorshift128',        'xorshift128p',       'xorshift128pp', 
    'xorshift128rp',      'xorshift64',         'xorshift64st',       'xorwow', 
    'xoshiro128p',        'xoshiro128pp',       'xoshiro256p',        'xoshiro256pp', 
    'xoshiro256stst',     'xsh',                'xtea',               'xtea2', 
    'xtea2',              'xxtea',              'ziff98',             
}

return {
    get_lib_headers = function() return lib_headers end,
    get_lib_sources = function() return lib_sources end,
    get_bat_sources = function() return bat_sources end,
    get_gen_sources = function() return gen_sources end
}
