#!/bin/lua
--
-- Creates build.ninja file for SmokeRand.
-- GCC, MinGW, ZIG CC (Clang) and MSVC compilers are supported. This script
-- can be used as a minimialistic replacement of CMake, especially for MSVC.
--
-- Known issues:
--
-- 1. Not all generators can be compiled for the 'gcc32' and 'mingw-hx' 32-bit
--    platform due to 128-bit arithmetics etc. Generators with AVX/AVX2
--    instructions are also excluded from the build for 32-bit platforms.
-- 2. MSVC headers dependency tracing may depend on the system locale because
--    ninja analyses stdout output of the MSVC compiler. Some issues with
--    encodings for non-latin based languages are possible. And this script
--    supports only English version of MSVC.
--

---------------------------------------------
----- Processing command line arguments -----
---------------------------------------------

local platform = ''
if #arg < 1 then
    print(
    [[Usage:
lua cfg_ninja.lua plaform
platform --- generic, gcc, mingw, gcc32, mingw-hx, msvc, zigcc
    generic     gcc-like compiler, no threads and x86 extensions.
    gcc, mingw  gcc compiler (POSIX threads).
    gcc32       gcc compiler, compilation of 32-bit binaries.
    mingw-hx    32-bit binaries friendly to HX DOS extender.
    zigcc       clang from Zig distribution (WinAPI threads).
]])
    return 0
else
    platform = arg[1]
end

-------------------------
----- List of files -----
-------------------------
cfg = require('cfg_data')
local lib_name = "$libdir/libsmokerand_core.a"
local batlib_name = "$libdir/libsmokerand_bat.a"
local lib_sources = cfg.get_lib_sources()
local bat_sources = cfg.get_bat_sources()
local gen_sources = cfg.get_gen_sources(false)

--------------------------------
----- Cross-platform rules -----
--------------------------------

local exe_ext, so_ext = '', '.so'
local stub, stub_crossplatform = '', [[
# NOTE: THIS FILE IS AUTOGENERATED BY cfg_ninja.lua!
# DON'T EDIT IT MANUALLY!
ninja_required_version = 1.3
srcdir = src
objdir = obj
bindir = bin
libdir = lib
includedir = include/smokerand
gen_bindir = $bindir/generators
gen_srcdir = generators
]]


-----------------------------------
----- Platform-specific rules -----
-----------------------------------

local exe_ext = ''
if os.getenv("OS") == "Windows_NT" then
    exe_ext, so_ext = '.exe', '.dll'
end

-- Rules for gcc/mingw, clang (zig cc)
local gcc_rules = [[
rule cc
    command = $cc -MMD -MT $out -MF $out.d $cflags -c -Iinclude $in -o $out
    description = CC $out
    depfile = $out.d
    deps = gcc

rule cpp
    command = $cxx -MMD -MT $out -MF $out.d $cxxflags -c -Iinclude $in -o $out
    description = CXX $out
    depfile = $out.d
    deps = gcc

rule cc89
    command = $cc -MMD -MT $out -MF $out.d $cflags89 -c -Iinclude $in -o $out
    description = CC $out
    depfile = $out.d
    deps = gcc


rule cc_gen
    command = $cc -MMD -MT $out -MF $out.d $gen_cflags -c -Iinclude $in -o $out
    description = CC $out
    depfile = $out.d
    deps = gcc

rule ar
    command = ar rcu $out $in
    description = AR $out

rule link
    command = $cc $linkflags $in -o $out $libs -Iinclude
    description = LINK $out

rule cpplink
    command = $cxx $linkflags $in -o $out $libs -Iinclude
    description = LINK $out
]]

-- Rules for MSVC
local msvc_rules = [[
rule cc
    command = $cc /showIncludes $cflags /c /Iinclude $in /Fo:$out
    description = CC $out
    deps = msvc

rule cc89
    command = $cc /showIncludes $cflags /c /Iinclude $in /Fo:$out
    description = CC $out
    deps = msvc

rule cc_gen
    command = $cc /showIncludes $cflags /c /Iinclude $in /Fo:$out
    description = CC $out
    deps = msvc

rule ar
    command = lib /OUT:$out $in
    description = AR $out

rule link
    command = link $linkflags $in $libs /Out:$out
    description = LINK $out
]]


function make_gcc_stub(cflags, gen_cflags, so_lflags, gen_lflags, compilers)
    if compilers == nil then
        compilers = "cc = gcc\ncxx = g++\n"
    end
    return "cflags = -std=c99 -O3 -Werror -Wall -Wextra " .. cflags .. "\n" ..
    "cxxflags = -std=c++11 -O3 -Werror -Wall -Wextra -Wno-attributes -march=native " .. cflags .. "\n" ..
    "cflags89 = -std=c89 -O3 -Werror -Wall -Wextra " .. cflags .. "\n" ..
    "exe_libs = -lm\nexe_linkflags = " .. so_lflags .. "\n" ..
    compilers ..
    "gen_cflags = $cflags -fPIC " .. gen_cflags .. "\n" ..
    "so_linkflags = -shared " .. so_lflags .. "\n" ..
    "gen_linkflags = -shared -fPIC " .. gen_lflags .. "\n"
end


if platform == 'generic' then
    local e_cflags = "-DNO_X86_EXTENSIONS -DNOTHREADS -DNO_CUSTOM_DLLENTRY";
    stub = make_gcc_stub(e_cflags, "", "", "") .. gcc_rules
    gen_sources = cfg.get_gen_sources(true) -- Only portable generators are supported
elseif platform == 'gcc' or platform == 'mingw' then
    local e_cflags, gen_cflags = "-march=native", "-ffreestanding -nostdlib"
    stub = make_gcc_stub(e_cflags, gen_cflags, "", gen_cflags) .. gcc_rules
elseif platform == 'gcc32' then
    local e_cflags, gen_cflags = "-march=i686 -m32", "-m32 -ffreestanding -nostdlib"
    stub = make_gcc_stub(e_cflags, gen_cflags, "-m32", gen_cflags) .. gcc_rules
    gen_sources = cfg.get_gen_sources(true) -- Only portable generators are supported
elseif platform == 'mingw-hx' then
    local e_cflags, gen_cflags = "-march=i686 -m32 -DUSE_WINTHREADS", "-m32"
    stub = make_gcc_stub(e_cflags, gen_cflags, "-m32", gen_cflags) .. gcc_rules
    gen_sources = cfg.get_gen_sources(true) -- Only portable generators are supported
elseif platform == 'zigcc' then
    local e_cflags, gen_cflags = "-march=native -DUSE_WINTHREADS", ""
    local compilers = "cc = zig cc\ncxx = zig cpp\n"
    stub = make_gcc_stub(e_cflags, gen_cflags, "", gen_cflags, compilers) .. gcc_rules
elseif platform == 'msvc' then
    exe_ext = '.exe'
    -- /WX if treat warnings as errors
    stub = "cflags = /O2 /W3 /arch:AVX2 /D_CRT_SECURE_NO_WARNINGS\n" ..
    "gen_cflags = $cflags\n" ..
    "cc = cl\n"..
    "exe_libs = advapi32.lib\n" ..
    "exe_linkflags = /SUBSYSTEM:CONSOLE\n" ..
    "so_linkflags = /DLL\n" ..
    "gen_linkflags = /DLL\n"

    stub = stub .. "\nmsvc_deps_prefix = Note: including file:\n"
    -- BEWARE OF LOCALES AND NON-ENGLISH OUTPUT FROM SOME INSTALLATIONS
    -- OF THE MSVC COMPILER!
--    stub = stub .. "\nmsvc_deps_prefix = Примечание: включение файла:\n"

    -- sourceDependencies requires at least VS 16.7 (2022)
    -- /sourceDependencies $out.json
    -- deps=msvc_source_dependencies in some unapproved ninja commits

--    stub = stub .. "\nmsvc_deps_prefix = Note: including file:\n"
    stub = stub .. msvc_rules
else
    error("Unknown platform '" .. platform .. "'")
    return 1
end

------------------------------------------------
----- build.ninja file contents generation -----
------------------------------------------------

print("Generating build.ninja for the '" .. platform .. "' platform...")

stub = stub_crossplatform .. "\n" .. stub .. "\n"

local default_builds = {}

function add_sources(sources)
    local objfiles = {}
    for _, f in pairs(sources) do
        local objfile = f:gsub("%.c", ".o")    
        if f == 'specfuncs' then
            io.write(string.format("build $objdir/%s: cc89 $srcdir/%s\n", objfile, f))
        else
            io.write(string.format("build $objdir/%s: cc $srcdir/%s\n", objfile, f))
        end
        table.insert(objfiles, "$objdir/" .. objfile)
    end
    return objfiles
end

function add_objfiles(objfiles)
    for _, f in pairs(objfiles) do
        io.write("    " .. f .. " $\n")
    end
    io.write("\n");
end

function add_exefile(exefile, extra_objfiles, rule)
    local srcext, linkrule = ".c", "link"
    if rule == "cpp" or rule == "cxx" then
        srcext = ".cpp"
        linkrule = "cpplink"
    end
    io.write("build $objdir/" .. exefile .. ".o: " .. rule .. " $srcdir/" .. exefile .. srcext .. "\n")
    local exefile_full = "$bindir/" .. exefile .. exe_ext
    io.write("build " .. exefile_full .. ": " .. linkrule .. " $objdir/" .. exefile .. ".o ")
    if #extra_objfiles > 0 then
        add_objfiles(extra_objfiles)
    else
        io.write("\n");
    end
    io.write("  libs = $exe_libs\n")
    io.write("  linkflags = $exe_linkflags\n")
    table.insert(default_builds, exefile_full)
end

local file = io.open("build.ninja", "w")
io.output(file)
io.write(stub)

-- Build core library
local lib_objfiles = add_sources(lib_sources)
io.write("build " .. lib_name .. ": ar ")
add_objfiles(lib_objfiles)

-- Build batteries library
local bat_objfiles = add_sources(bat_sources)
io.write("build " .. batlib_name ..": ar ")
add_objfiles(bat_objfiles)

-- Build batteries

-- Build the command line tool executable
--table.insert(bat_objfiles, lib_name)
add_exefile("smokerand", {batlib_name, lib_name}, "cc")
add_exefile("test_funcs", {lib_name}, "cc")
add_exefile("test_rdseed", {lib_name}, "cc")
add_exefile("testgens", {batlib_name, lib_name}, "cc")
add_exefile("test_cpp11", {batlib_name, lib_name}, "cpp")
add_exefile("calibrate_dc6", {lib_name}, "cc")
add_exefile("calibrate_linearcomp", {lib_name}, "cc")
-- Build extra executables: PE32 hack
io.write("build $objdir/pe32loader.o: cc $srcdir/pe32loader.c\n")
io.write("build $objdir/peparse.o: cc $srcdir/peparse.c\n")
io.write("build $bindir/peparse" .. exe_ext .. ": link $objdir/pe32loader.o $objdir/peparse.o " .. batlib_name .. " " .. lib_name .. "\n")
io.write("  libs = $exe_libs\n")
io.write("  linkflags=$exe_linkflags\n")
table.insert(default_builds, "$bindir/peparse" .. exe_ext)
-- Build extra executables: C89 compatible version
io.write("build $objdir/sr_tiny.o: cc89 $srcdir/sr_tiny.c\n")
io.write("build $bindir/sr_tiny" .. exe_ext .. ": link $objdir/sr_tiny.o $objdir/specfuncs.o\n")
io.write("  libs = $exe_libs\n")
io.write("  linkflags=$exe_linkflags\n")
table.insert(default_builds, "$bindir/sr_tiny" .. exe_ext)

-- Build generators
for _, f in pairs(gen_sources) do
    local gen_fullname = "$gen_bindir/lib" .. f .. so_ext
    io.write("build $gen_bindir/obj/" .. f .. ".o: cc_gen $gen_srcdir/" .. f .. ".c\n")
    io.write("build " .. gen_fullname .. ": link $gen_bindir/obj/" .. f .. ".o\n")
    table.insert(default_builds, gen_fullname)
    if f == "crand" then
        io.write("    linkflags = $so_linkflags\n\n");
    else
        io.write("    linkflags = $gen_linkflags\n\n");
    end
end

-- Default rules
io.write("default ")
for k, v in pairs(default_builds) do
    io.write(v .. " ")
    if k % 2 == 0 then
        io.write("$\n    ")
    end
end
io.write("\n\n")

-- Finish the work
io.close(file)
io.output(io.stdout)
print("Success")
