#!/bin/lua
--
-- Creates Open Watcom WMake file for Windows NT target. This script uses
-- an approach similar to ninja build system: doesn't try to use wildcards
-- in rules, advanced wmake options etc.
--
-- Open Watcom C can compile only for 16- and 32-bit platforms and its support
-- of x86 is limited by Pentium Pro subset. The next issues should be taken
-- into account:
--
-- 1. Different calling conventions and name mangling may be used by
--    the Open Watcom compiler. We use '-6s' flag to use cdecl instead of
--    default watcall / WATCOM_C.
-- 2. Some combinations of keys for wcl386 may cause incorrect linking
--    of DLLs with PRNGs (they would crash).
-- 3. Some PRNGs, especially some 64-bit PRNGs and most CSPRNGs may be
--    very slow in comparison to modern x86-64 compilers.
-- 4. Too many threads (more than 2) may cause program crashes, probably due
--    to memory limitations.
-- 5. 32-bit DOS builds are not supported, use software like HX DOS Extender,
--    WDOSX or DOSWIN32 together with DOSLFN to obtain 32-bit implementation
--    for DOS.
--

cfg = require('cfg_data')

local lib_sources = cfg.get_lib_sources()
local bat_sources = cfg.get_bat_sources()
local lib_headers = cfg.get_lib_headers()
local gen_sources = cfg.get_gen_sources(true)

local file = io.open("Makefile.wat", "w")
io.output(file)

-- Generic rules
io.write([[# NOTE: THIS FILE IS AUTOGENERATED BY cfg_wmake.lua!
# DON'T EDIT IT MANUALLY!
cflags = -q -otexanhi -d0 -6s -za99 -bm -bt=nt -Iinclude -DNO_X86_EXTENSIONS -DUSE_WINTHREADS
cc = wcc386
lnk = wcl386
srcdir = src
objdir = obj
bindir = bin
libdir = lib
includedir = include/smokerand
gen_bindir = $(bindir)\\generators
gen_srcdir = generators
]])

-- Make "all" section
io.write("all: $(bindir)/smokerand.exe")
for _, g in pairs(gen_sources) do
    local dllfile = " $(gen_bindir)/lib" .. g .. ".dll"
    io.write(dllfile)
end
io.write("\n")


-- Make the program executable
-- a) Line with dependencies
local sources = {}
for _, v in pairs(lib_sources) do
    table.insert(sources, v)
end
for _, v in pairs(bat_sources) do
    table.insert(sources, v)
end
table.insert(sources, "smokerand.c")
local objstr = ""
for _, v in pairs(sources) do
    objstr = objstr .. " $(objdir)/" .. v:gsub("%.c", ".obj")
end
-- b) Line with commands
io.write("$(bindir)/smokerand.exe:" .. objstr .. "\n")
io.write("\twcl386 -4s -fe=$(bindir)/smokerand.exe " .. objstr .. "\n")

-- Prepare list of library core headers
local lib_headers_str = "include/smokerand_core.h "
for _, v in pairs(lib_headers) do
    lib_headers_str = lib_headers_str .. " $(includedir)/" .. v
end

-- Object file with the main() function
io.write("$(objdir)/smokerand.obj: $(srcdir)/smokerand.c " .. lib_headers_str .. "\n")
io.write("\twcc386 $(cflags) -fo=$(objdir)/smokerand.obj $(srcdir)/smokerand.c\n")

-- Compile the library core sources
for _, v in pairs(lib_sources) do
    local cfile, objfile = "$(srcdir)/" .. v, "$(objdir)/" .. v:gsub("%.c", ".obj")
    io.write(objfile .. ": " .. cfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags) -fo=" .. objfile .. " " .. cfile .. "\n")
end

-- Compile the batteries sources
for _, v in pairs(bat_sources) do
    local cfile   = "$(srcdir)/" .. v
    local objfile = "$(objdir)/" .. v:gsub("%.c", ".obj")
    local hfile   = "$(includedir)/" .. v:gsub("%.c", ".h")
    io.write(objfile .. ": " .. cfile .. " " .. hfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags) -fo=" .. objfile .. " " .. cfile .. "\n")
end

-- Compile the generators
for _, g in pairs(gen_sources) do
    local cfile = "$(gen_srcdir)/" .. g .. ".c"
    local objfile = "$(gen_bindir)/obj/" .. g .. ".obj"
    local dllfile = "$(gen_bindir)/lib" .. g .. ".dll"
    --dllstr = dllstr .. dllfile
    io.write(objfile .. ": " .. cfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags) " .. cfile .. " -bd -Iinclude -fo=" .. objfile .. "\n")
    io.write(dllfile .. ": " .. objfile .. "\n")
    io.write("\twcl386 " .. objfile .. " -fe=" .. dllfile .. " -l=nt_dll -bd -q\n")
end

-- Make "clean" section
io.write("clean: .SYMBOLIC\n")
io.write("\tdel $(bindir)\\smokerand.exe\n")
io.write("\tdel $(objdir)\\*.obj\n")
io.write("\tdel $(gen_bindir)\\obj\\*.obj\n")
io.write("\tdel $(gen_bindir)\\*.dll\n")

-- Finish the work
io.close(file)
io.output(io.stdout)
print("Success")

