#!/bin/lua
--
-- Creates Open Watcom WMake file for Windows NT target. This script uses
-- an approach similar to ninja build system: doesn't try to use wildcards
-- in rules, advanced wmake options etc.
--
-- Open Watcom C can compile only for 16- and 32-bit platforms and its support
-- of x86 is limited by Pentium Pro subset. The next issues should be taken
-- into account:
--
-- 1. Different calling conventions and name mangling may be used by
--    the Open Watcom compiler. We use '-6s' flag to use cdecl instead of
--    default watcall / WATCOM_C.
-- 2. Some combinations of keys for wcl386 may cause incorrect linking
--    of DLLs with PRNGs (they would crash).
-- 3. Some PRNGs, especially some 64-bit PRNGs and most CSPRNGs may be
--    very slow in comparison to modern x86-64 compilers.
-- 4. Too many threads (more than 2) may cause program crashes, probably due
--    to memory limitations.
--
-- This script will create makefile that will compile SmokeRand for two
-- platforms: Windows NT (32-bit only) and DOS (both 16-bit and 32-bit).
--
-- 1. For Windows NT executables are compiled as usual. But DLLs are compiled
--    as freestanding. It required some hacks with compiler and linker keys;
--    also $(%WATCOM)/lib386/dos/clib3s.lib C runtime library is used instead
--    of runtime for Windows NT: we need some functions for 64-bit integers
--    but not DLL stubs, runtime library etc. 
-- 2. 16-bit DOS version is compiled from `sr_tiny.c` and `specfuncs.c`. It
--    provides the `express` battery for 16-bit computers.
-- 3. 32-bit DOS version is compiled for DOS extenders such as DOS/32, PMODEW
--    or CauseWay. It DOES SUPPORT loading of Win32 DLLs without exports:
--    it is made by a custom `pe32loader.c`.
--
-- An alternative way to build it under DOS is to use Windows NT build and
-- software like HX DOS Extender, WDOSX or DOSWIN32 together with DOSLFN to
-- obtain 32-bit implementation for DOS. But it may require proprietary DLLs
-- such as MSVCRT.DLL.
--
-- (c) 2025 Alexey L. Voskov, Lomonosov Moscow State University
-- alvoskov@gmail.com
--
-- This software is licensed under the MIT license.
--

cfg = require('cfg_data')

-- About DOS extenders: %WATCOM%\BINW should be added to the path:
-- it will help to automatically stubify the resulting EXE.
--
local dosextender = "dos32a"
local lib_sources = cfg.get_lib_sources()
local bat_sources = cfg.get_bat_sources()
local lib_headers = cfg.get_lib_headers()
local gen_sources = cfg.get_gen_sources(true)

local file = io.open("Makefile.wat", "w")
io.output(file)

-- Generic rules
io.write([[# NOTE: THIS FILE IS AUTOGENERATED BY cfg_wmake.lua!
# DON'T EDIT IT MANUALLY!
cflags_generic = -s -q -otexanh -oe -d0 -6s -za99 -bm -Iinclude
cflags = $(cflags_generic) -bt=nt -DNO_X86_EXTENSIONS -DUSE_WINTHREADS
cflags_dos32 = $(cflags_generic) -bt=DOS -DNOTHREADS -DNO_POSIX
cc = wcc386
lnk = wcl386
appsrcdir = apps
srcdir = src
objdir = obj
objdir_dos32 = dos32
bindir = bin
libdir = lib
dll_runtime = $(%WATCOM)/lib386/dos/clib3s.lib
includedir = include/smokerand
gen_bindir = $(bindir)\\generators
gen_srcdir = generators
]])

-- Make "all" section
io.write("all: $(bindir)/smokerand.exe $(bindir)/sr_dos32.exe $(bindir)/srtiny16.exe")
for _, g in pairs(gen_sources) do
    local dllfile = " $(gen_bindir)/" .. g .. ".dll"
    io.write(dllfile)
end
io.write("\n")


-- Make the program executable
-- a) Line with dependencies
local sources = {}
for _, v in pairs(lib_sources) do
    table.insert(sources, v)
end
for _, v in pairs(bat_sources) do
    table.insert(sources, v)
end
table.insert(sources, "smokerand.c")
local objstr, objstr_dos32 = "", ""
for _, v in pairs(sources) do
    objstr = objstr .. " $(objdir)/" .. v:gsub("%.c", ".obj")
    objstr_dos32 = objstr_dos32 .. " $(objdir_dos32)/" .. v:gsub("%.c", ".obj")
end
objstr_dos32 = objstr_dos32 .. " $(objdir_dos32)/pe32loader.obj"
-- b) Line with commands
io.write("$(bindir)/smokerand.exe:" .. objstr .. "\n")
io.write("\twcl386 -4s -fe=$(bindir)/smokerand.exe " .. objstr .. "\n")

io.write("$(bindir)/sr_dos32.exe:" .. objstr_dos32 .. "\n")
io.write("\twcl386 -4s -fe=$(bindir)/sr_dos32.exe -bcl=" .. dosextender ..
    " " .. objstr_dos32 .. "\n")


-- Prepare list of library core headers
local lib_headers_str = "include/smokerand_core.h "
for _, v in pairs(lib_headers) do
    lib_headers_str = lib_headers_str .. " $(includedir)/" .. v
end

---------- Object file with the main() function ----------
io.write("$(objdir)/smokerand.obj: $(appsrcdir)/smokerand.c " .. lib_headers_str .. "\n")
io.write("\twcc386 $(cflags) -fo=$(objdir)/smokerand.obj $(appsrcdir)/smokerand.c\n")

io.write("$(objdir_dos32)/smokerand.obj: $(appsrcdir)/smokerand.c " .. lib_headers_str .. "\n")
io.write("\twcc386 $(cflags_dos32) -fo=$(objdir_dos32)/smokerand.obj $(appsrcdir)/smokerand.c\n")

io.write("$(objdir_dos32)/pe32loader.obj: $(srcdir)/pe32loader.c " .. lib_headers_str .. "\n")
io.write("\twcc386 $(cflags_dos32) -fo=$(objdir_dos32)/pe32loader.obj $(srcdir)/pe32loader.c\n")

---------- Compile the 16-bit version ----------
io.write("$(bindir)/srtiny16.exe: $(objdir_dos32)/srtiny16.obj $(objdir_dos32)/spfunc16.obj\n")
io.write("\twcl -s -q -otexanh $(objdir_dos32)/srtiny16.obj $(objdir_dos32)/spfunc16.obj " ..
    "-fe=$(bindir)/srtiny16.exe\n")
io.write("$(objdir_dos32)/srtiny16.obj: $(appsrcdir)/sr_tiny.c\n")
io.write("\twcc -s -q -otexanh $(appsrcdir)/sr_tiny.c -fo=$(objdir_dos32)/srtiny16.obj -Iinclude\n")
io.write("$(objdir_dos32)/spfunc16.obj: $(srcdir)/specfuncs.c\n")
io.write("\twcc -s -q -otexanh $(srcdir)/specfuncs.c -fo=$(objdir_dos32)/spfunc16.obj -Iinclude\n")

---------- Object files for Windows NT ----------
-- Compile the library core sources
for _, v in pairs(lib_sources) do
    local cfile, objfile = "$(srcdir)/" .. v, "$(objdir)/" .. v:gsub("%.c", ".obj")
    io.write(objfile .. ": " .. cfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags) -fo=" .. objfile .. " " .. cfile .. "\n")
end

-- Compile the batteries sources
for _, v in pairs(bat_sources) do
    local cfile   = "$(srcdir)/" .. v
    local objfile = "$(objdir)/" .. v:gsub("%.c", ".obj")
    local hfile   = "$(includedir)/" .. v:gsub("%.c", ".h")
    io.write(objfile .. ": " .. cfile .. " " .. hfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags) -fo=" .. objfile .. " " .. cfile .. "\n")
end

---------- Object files for DOS32 ----------
for _, v in pairs(lib_sources) do
    local cfile, objfile = "$(srcdir)/" .. v, "$(objdir_dos32)/" .. v:gsub("%.c", ".obj")
    io.write(objfile .. ": " .. cfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags_dos32) -fo=" .. objfile .. " " .. cfile .. "\n")
end

-- Compile the batteries sources
for _, v in pairs(bat_sources) do
    local cfile   = "$(srcdir)/" .. v
    local objfile = "$(objdir_dos32)/" .. v:gsub("%.c", ".obj")
    local hfile   = "$(includedir)/" .. v:gsub("%.c", ".h")
    io.write(objfile .. ": " .. cfile .. " " .. hfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags_dos32) -fo=" .. objfile .. " " .. cfile .. "\n")
end


---------- Compile the generators ----------
-- A simple hack for compiling without RUNTIME.
-- wcc386 -s -d0 -bm -bt=nt -6s -za99 generators/lcg69069.c -Iinclude -fo=lcg69069.obj
-- wcl386 lcg69069.obj d:/watcom/lib386/dos/clib3s.lib -fe=lcg69069.dll -q -6s -bd -bcl=nt_dll
for _, g in pairs(gen_sources) do
    local cfile = "$(gen_srcdir)/" .. g .. ".c"
    local objfile = "$(gen_bindir)/obj/" .. g .. ".obj"
    local dllfile = "$(gen_bindir)/" .. g .. ".dll"
    --dllstr = dllstr .. dllfile
    io.write(objfile .. ": " .. cfile .. " " .. lib_headers_str .. "\n")
    io.write("\twcc386 $(cflags) " .. cfile .. " -Iinclude -fo=" .. objfile .. "\n")
    io.write(dllfile .. ": " .. objfile .. "\n")
    io.write("\twcl386 " .. objfile .. " $(dll_runtime) -fe=" .. dllfile ..
        " -q -bd -bcl=nt_dll -\"OPTION NODEFAULTLIBS\"\n")
end

-- Make "clean" section
io.write("clean: .SYMBOLIC\n")
io.write("\tdel $(bindir)\\smokerand.exe\n")
io.write("\tdel $(objdir)\\*.obj\n")
io.write("\tdel $(gen_bindir)\\obj\\*.obj\n")
io.write("\tdel $(gen_bindir)\\*.dll\n")

-- Finish the work
io.close(file)
io.output(io.stdout)
print("Success")

